### ISSUE TITLE
Swapper2

### ISSUE THREAD

**Issue by felixwilhelm** [OliverSch/compiler#100]
Gibt für unser Backend "2 4" aus und sollte "3 4" ausgeben. Das klappt auch für das Firm Backend. 
Problem liegt also potentiell irgendwo in unseren Peephole Optimierung

**Comment by felixwilhelm** [comment]
Wir erzeugen den Code für die swap Funktion:
````
 movq     $2, %rcx
 movq     $3, %rdi
 movq     $4, %rdi
 movq     $1, %r8
````

Die zweite Zuweisung zu rdi ist natürlich nicht ok.

**Comment by kit-fw** [comment]
Fehler liegt nicht bei der PeepholeOptimization Klasse.
Sieht für mich danach aus als wäre das Prob schon irgendwo im SlotAllocator

**Comment by kit-fw** [comment]
Das Problem ist im SlotAllocator. Zwei lokale Phi Nodes kriegen den gleichen Slot zugewiesen obwohl das eigentlich nicht der Fall sein sollte. Finde auf die schnelle den Fehler aber nicht.

@olydis kannst du da bis morgen noch einmal drauf schauen?

**Comment by olydis** [comment]
blöde frage: wo/was ist Swapper2? finde die Datei weder im repo noch irgendne mail mit quelltext oder so

**Comment by felixwilhelm** [comment]
Im Anhang der letzten mail von Sebastian. Hab sie dir weitergeleitet ;)
Am 08.02.2015 08:30 schrieb "Johannes" <notifications@github.com>:

**Comment by OliverSch** [comment]
Moin, hochgeladen: https://github.com/OliverSch/compiler/commit/c7c0e9c8fd1d906990fa79261c266dc2e0178e71

**Comment by olydis** [comment]
merci
