### ISSUE TITLE
InfiniteLoops

### ISSUE THREAD

**Issue by OliverSch** [OliverSch/compiler#101]
```
===TESTCASE===
InfiniteLoops
---CUSTOM---
InfiniteLoops.s: Assembler messages:
InfiniteLoops.s:14: Error: operand size mismatch for `movq'
InfiniteLoops.s:30: Error: operand size mismatch for `movq'
InfiniteLoops.s:39: Error: operand size mismatch for `movq'
InfiniteLoops.s:55: Error: operand size mismatch for `movq'
Created program InfiniteLoops
```

**Comment by felixwilhelm** [comment]
Den Testcase hab ich nicht ? ;)

**Comment by felixwilhelm** [comment]
Die Mem Nodes die wir für Endlosschleifen einfügen mussten werden zu "movq (mem), $0". Ich sitze dran das zu fixen.

**Comment by felixwilhelm** [comment]
9ea9cb4ad1379b34a79eee7907d5eab65637fe27 fixt die movs. Wir haben aber immer noch Probleme mit Endlosschleifen:

- Durch Method Inlining + Constant Folding wird der folgende Code beim ConstantFolding von InfiniteLoops getriggert:
````
      // replace 100% Conds with Jmp
                if (node instanceof Cond) {

                    // get right child
                    for (BackEdges.Edge edge : BackEdges.getOuts(node)) {
                        Proj alt = (Proj) edge.node;
                        if (alt.getNum() == (tv.equals(TargetValue.getBTrue()) ? 1 : 0)) {
                            Graph.exchange(alt, graph.newJmp(alt.getBlock()));
                        } else {
                            System.out.println(alt);
                            System.out.println(alt.getBlock());
                            Graph.exchange(alt, graph.newBad(Mode.getX()));
                        }
````

Dadurch bekommen wir Blocks (nach der Endlosschleife) die keine Control Flow Preds mehr haben, aber immer noch einen Predecessor durch die Mem Phi Nodes. Das bringt zum Einen das Firm Backend zum Absturz (verify Warnung wegen Blocks ohne Kontrollflussvorgänger) und zum Anderen kommt eine unserer späteren Optimierungen damit nicht zurecht und die komplette Schleife wird wegoptimiert.

Meiner Meinung nach müsste man hier den kompletten Block irgendwie als Bad markieren aber dabei renne ich immer in libfirm Assertions.

**Comment by OliverSch** [comment]
Oh da hab ich au schon vorhin paar Stunden rum gemacht. libfirm hat sich bei mir auch immer beschwert :(

**Comment by felixwilhelm** [comment]
Der letzte Commit killt die Blöcke korrekt. Sieht ganz gut aus.

**Comment by felixwilhelm** [comment]
Wir laufen immer noch in Firm Assertions bei --compile-firm die entstehen aber durch das Method Inlining. Ich kümmer mich drum.

**Comment by kit-fw** [comment]
Fixed :)

**Comment by OliverSch** [comment]
Very nice :)
