### ISSUE TITLE
Abgabe

### ISSUE THREAD

**Issue by OliverSch** [OliverSch/compiler#105]
Wer macht die Abgabe? Der mit dem letzten commit?

**Comment by kit-ssl** [comment]
Ich werde um 22:00 Uhr alles durchsehen und die Ausführung auf einem neuen System testen. Danach schreibe ich die eMail.

**Comment by OliverSch** [comment]
sehr gut :)

**Comment by felixwilhelm** [comment]
Denkt bitte auch an die Abgabe der drei Testcases :)

**Comment by kit-ssl** [comment]
wo finde ich sie?

**Comment by felixwilhelm** [comment]
@TobiasRp Test ist hier: https://github.com/OliverSch/compiler/commit/607a45d75cff787b4d837ffba1d1cdd41fbf21fc

Mehr scheinen nicht gemacht worden zu sein.

**Comment by OliverSch** [comment]
Ja ich glaub Christian hat keinen mehr hinbekommen. Ich hab lieber an den slides und optimierungen gebastelt.

**Comment by OliverSch** [comment]
> Eine README-Datei im Repo, die beschreibt, was man zum Kompilieren 
des Compilers benötigt, wie man den Compiler kompiliert und wo sich das 
Run-Skript befindet. 

Uns fehlt glaube ich noch die Info das man maven benötigt.
