### ISSUE TITLE
Optimize arithmetic expressions

### ISSUE THREAD

**Issue by OliverSch** [OliverSch/compiler#73]
...like * 2^n, / 2^n.

**Comment by OliverSch** [comment]
div durch mult,...

**Comment by felixwilhelm** [comment]
fannkuch output includes code like this: 

	movl     $2, %ebx
	idivl    %ebx
	movq     %rdx, %rsi
	movq     %rdx, %rsi

Any idea why this is not optimized to a shift and why there is an additional mov?

**Comment by OliverSch** [comment]
Sehr gute Frage. Ich schaue es mir gleich an.

**Comment by OliverSch** [comment]
@felixwilhelm Das müsste von folgendem Teil stammen: 

```
         if (permCount%2 == 0)
           checksum = checksum + flipsCount;
         else
           checksum = checksum - flipsCount;
```

`x % 2` wird momentan von uns noch nicht optimiert. Im Prinzip müsste man das durch ein `andl` mit der entsprechenden Bitmaske ersetzten können. Das Problem ist, das dies nicht so einfach ist, wenn `x` negativ ist. Falls du eine Idee hast, wäre cool. Ich bin hier im Moment ratlos.

Wo das zweite `movq` herkommt kann ich dir leider auch nicht sagen...

```
        @Override
        public void visit(Mod node) {
            Block b = (Block) node.getBlock();

            prepareNode(node);
            Operand left = getOp(node.getLeft());
            Operand right = getOp(node.getRight());
            Operand result = getOp(node);

            if (result.getType() == OperandType.CONSTANT) {
                return;
            }

            function.addInstruction(Instruction.movl(left, Operand.newRegister(Register.RAX)));
            function.addInstruction(Instruction.cltd());
            function.addInstruction(Instruction.idivl(right));
            function.addInstruction(Instruction.movq(Operand.newRegister(Register.RDX), result));
        }
```

**Comment by felixwilhelm** [comment]
Kann das sein dass einer der Commits gestern heftig Performance Regressions ausgelöst hat? Das speedcenter zeigt starke Verschlechterung bei Pi und mandelbrot

**Comment by OliverSch** [comment]
Das liegt an dem fix für #95. div auf 64bit ist super langsam.
