### ISSUE TITLE
Extend CLI to support parameterization of interpreter:

### ISSUE THREAD

**Issue by olydis** [OliverSch/compiler#77]
Take a look at the compilers Main.java, line 72/73.
As you can see, our backend is currently configured to not run the interpreter at all (`InterpretationStrategy.none()`).
It would be nice to support the other `InterpretationStrategy`s using CLI parameters...

Benefit:
* better TESTING! 
    * if you work on an optimization, you do NOT want the interpreter to run (so you can compare line count etc.)
    * to debug the interpreter, you can specify a specific number of simulation steps to perform before baking the state into the binary (scenario: interpretation seems to break whenever it is interrupted right in front of a "call" instruction... have fun debugging that without exact control over the number of instructions executed)
    * to measure the impact of interpretation time on final runtime, it is vital to specify the maximum time the compiler is allowed to take...
* better control over compilation quality by the user (e.g. if you want the fastest assembly for our testcase "Pi", just let the compiler run for an hour :D )
* let the Betreuers be able to play

Note: all these behaviours are already implemented, we just need them to be selectable using CLI!

**Comment by TobiasRp** [comment]
Implemented.
Usage: --interpreter=none | forever | instructions-<count> | for-<seconds>
e.g. --interpreter=for-60 to execute the interpreter for 60 seconds. 

I haven't added the strategy until <date> since that is rather complex and (correct me if I'm wrong) probably not so important.

**Comment by olydis** [comment]
PERFECT *.*
