### ISSUE TITLE
Optimize implementation of "print_int"

### ISSUE THREAD

**Issue by olydis** [OliverSch/compiler#79]

**Comment by TobiasRp** [comment]
I don't know how to improve print_int. What other function to use than printf?
The only thing I can think of is sprintf + write and that does seem worse than printf. Remember, we have to convert an integer to a char array somehow...

**Comment by olydis** [comment]
char str[16]; // should be enough for INT_MIN…

itoa(number, str, 10);

puts(str);

**Comment by TobiasRp** [comment]
itoa is not in the standard but should work on linux/mac. I'll implement and test it later

**Comment by TobiasRp** [comment]
Itoa doesn't work with my GCC (4.9.1). I will just close this issue since I don't think it really matters that much and I doubt that the itoa or similar solution would make a difference
