### ISSUE TITLE
Improve Register Allocation

### ISSUE THREAD

**Issue by felixwilhelm** [OliverSch/compiler#81]
- Better Cycle Detection
- Only Use/Restore registers actually used
- Library functions should save/restore all potentially corrupted registers. This makes more registers available for allocation
- Improve call free detection to Block instead of functions
- Improve lifetime analysis from Block to Instructions.

**Comment by olydis** [comment]
Implemented so far:
- only use/restore regs actually used
- call free detection on instruction level, WITHIN one block (so no analysis of code that might execute between blocks)

**Comment by felixwilhelm** [comment]
Implemented:
- Library functions should save/restore all potentially corrupted registers. This makes more registers available for allocation

Results in good speedup for Pi.mj

**Comment by felixwilhelm** [comment]
Allowing usage of rdi and rsi actually makes fannkuch slower right now, because it will result in a less optimal register allocation m(.

**Comment by felixwilhelm** [comment]
@olydis: Can we easily implement something like preferred register allocation to certain nodes? For fannkuch we can get a serious speed up if all Phi nodes are stored as registers.

**Comment by olydis** [comment]
We can :) 

In the register allocator in AssemblerFunction, change the comparator to sort the priority queue from what it is now (#uses descending) to something else! 

I guess the information about Phi nodes is lost at this point, so I would probably add a “weight” field or something to OperandSlot’s that we can initialize in SlotAllocator, where we still have the connection between Slots and Nodes :) Unfortunately, I won’t have time today, so feel free :P 

Also: I guess we don’t need the block information in OperandSlot anymore – serious simplification/cleanup potential :D

**Comment by felixwilhelm** [comment]
Done with Commit 04c8a1b5f5cabff0fb3b4b95c8aaca165b4e81fb. This introduces priority nodes that get an increased useCount. Adding priority to all nodes used in comparisons gives quite good results.
