### ISSUE TITLE
memory path optimization

### ISSUE THREAD

**Issue by olydis** [OliverSch/compiler#84]
- move load's as far "up" the path as possible
- merge adjacent load's/store's
- remove stores adjacent to main's end
- replace loads adjacent to main's start

**Comment by OliverSch** [comment]
I did start it in the `move-loads-up` branch. Maybe you can use something from there. It works well for "simple loops"

**Comment by olydis** [comment]
Oh cool das werd ich gern verwenden! 😊





From: Oliver
Sent: ‎Tuesday‎, ‎January‎ ‎27‎, ‎2015 ‎5‎:‎40‎ ‎PM
To: OliverSch/compiler
Cc: Johannes Bader





I did start it in the move-loads-up branch. Maybe you can use something from there. It works well for "simple loops"

**Comment by olydis** [comment]
On hold. Even transforming OliverLoop.mj (in a formally CORRECT fashion) is comparable to voodoo
