### ISSUE TITLE
CSE + Constant Optimization does not trigger

### ISSUE THREAD

**Issue by felixwilhelm** [OliverSch/compiler#87]
This seems to be the reason why we are extremly slow for programs like Pi.

	int scale = 400000000;
		int i = 3;
		boolean plus = false;
		int currVal = scale;
		int maxInt = pi.getMaxInt();
		System.out.println(maxInt);
		while (i < maxInt) {
			if (plus) {
				currVal = currVal + scale / i;
			} else {
				currVal = currVal - scale / i;
			}

scale / i is not calculated once before the loop but instead calculated again for each iteration. 
Does someone has any ideas why this might the case?

**Comment by felixwilhelm** [comment]
Vergesst es habe die Addition zu i übersehen ...

**Comment by olydis** [comment]
Ah sehs jetzt erst...

-          Jap genau und die divisionen finden wenn ich mich recht entsinn in verschiedenen GBs statt, da macht CSE gerade zur Vorsicht nichts (Dominanzanalyse hilft evtl)

-          Die spruenge zuruck im speedcenter sind 1. manchmal random (hab for wenigen tagen mal einfach mit nur refactoring gepusht, wir wurden dabei schlechter...) und zum anderen durch ne leicht fehlerhafte Optimierung vorgerufen (hab Phi’s versucht besser zu behandeln, zum Glueck sind dabei die Simon_146/147-Testfaelle explodiert, hab aber leider erst nach push vollstaendig getestet – ich dachte mir: wenn MMul, Pi und fannkuch korrekt laeuft kann mans ja mal hochladen und sich schonmal die neuen Messungen anschaun waehrend man compareAll abfeuert ;) )...

 

Naaa wie stehts mit inlining? :D
