### ISSUE TITLE
Floating point exception

### ISSUE THREAD

**Issue by OliverSch** [OliverSch/compiler#95]
The following minjava-program throws a Floating point exception:
```
class a {
	public static void main(String[] args) {
		System.out.println(-2147483648/(-1));
	}
}
```

Expected output (javac): `-2147483648`

**Comment by olydis** [comment]
:+1:

**Comment by olydis** [comment]
wait, the FIRM backend also triggers an FPE ^^ i don't see any way to fix this except adding a check ==> expensive as f*** ==> not even firm does it ==> in the end we're the only ones

**Comment by OliverSch** [comment]
@olydis Seems to be still not fixed...

```
class a {
	public int b;
	public int c;
	public static void main(String[] args) {
		System.out.println(-2147483648/(-1));
		a a = new a();
		a.b = -2147483648;
		a.c = -1;
		System.out.println(a.b/a.c);
	}
}
```

**Comment by olydis** [comment]
sh** this is crazy to fix

**Comment by OliverSch** [comment]
An conditional jump seems to be much faster. I think we should change this anyway.

**Comment by olydis** [comment]
Agree, but probably have no time til tomorrow

**Comment by OliverSch** [comment]
Scheint doch zu laufen, ich hatte es irgendwie mit firm noch getestet...

**Comment by OliverSch** [comment]
Also hier läuft alles mit der div auf 64bit, allerdings ist das natürlich super lahm wie man im pi-Test sieht. Ein conditional jump wäre schneller.
