### ISSUE TITLE
Foo

### ISSUE THREAD

**Issue by OliverSch** [OliverSch/compiler#99]
```
class Foo {
	public static void main(String[] args) {
		int x = 42;
		if (false);
		if (x != x);
		if (false);
		if (42 != 42);
		if (x != x);
	}
}
```

results in an endless loop:

```
	.text
	.globl main
	.p2align 4,,15
	.type main, @function
main:
	movl     $42, %eax
	cmpl     $42, %eax
	je       .L85
	.p2align 4,,15
.L94:
	.p2align 4,,15
.L85:
	jmp      .L94
	.p2align 4,,15
.L125:
	movq     $0, %rax
	ret      
	jmp      .L125
	.size main, .-main
```

**Comment by OliverSch** [comment]
Ok it seems to be the `MergeBasicBlocks` optimization that moves a jump to a wrong block.

**Comment by felixwilhelm** [comment]
We create really ugly firm graphes when handling stuff like "if (true)" . My last commit fixes that.

**Comment by OliverSch** [comment]
Das behebt das Problem nicht wirklich oder? Wenn die Konstantenfaltung den Graph umbaut und dadurch der Firmgraph wieder "komisch" wird, dann kommt es wieder zu dem Bug.

Das Problem scheint folgendes zu sein: `graph.keepAlive(node.getBlock());` erstellt eine Kante vom End-Node zu dem Block. Dies verwirrt die `MergeBasicBlocks` Optimierung.

**Comment by felixwilhelm** [comment]
Da hast du Recht. Das keepAlive das du gefixt hast hab ich lange gesucht, aber nicht gefunden :) Mein if/else commit ist dann eigentlich nicht mehr unbedingt nötig, aber haut direkt einen ganzen Haufen Bad Blocks raus die uns später Probleme bereiten könnten. 

Gute Arbeit ! :)
